# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sentinel_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: sentinel_redis
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentinel_fastapi
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:                # <--- ADD THIS
      - .env                 # <--- ADD THIS
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app/backend

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentinel_celery
    command: celery -A backend.celery_app worker --loglevel=info --pool=gevent
    env_file:                # <--- ADD THIS
      - .env                 # <--- ADD THIS
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./backend:/app/backend
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentinel_react
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Enables hot-reloading for UI dev
      - /app/node_modules

volumes:
  mongo_data: