import time
import uuid
from backend.workflow import app_graph
from backend.memory.db import save_research_run

def run_research_pipeline(user_query: str, task_id: str = None):
    """Executes the LangGraph pipeline synchronously for FastAPI BackgroundTasks."""
    # Fallback UUID in case it's called directly outside the router
    current_task_id = task_id or str(uuid.uuid4())
    
    current_state = {
        "user_request": user_query,
        "research_plan": [],
        "current_topic": "",
        "collected_research": [],
        "final_report": "",
        "loop_count": 0,
        "metrics": {
            "total_cost": 0.0, 
            "total_prompt_tokens": 0, 
            "total_completion_tokens": 0, 
            "node_latencies": {}
        }
    }
    
    start_time = time.perf_counter()
    
    try:
        # Stream the LangGraph execution natively
        for event in app_graph.stream(current_state):
            for node_name, state_update in event.items():
                current_state.update(state_update)
                # Celery self.update_state() removed. 
                # FastAPI routes.py handles the PENDING -> SUCCESS state transition.

        elapsed_latency = round(time.perf_counter() - start_time, 2)
        report = current_state.get("final_report", "").strip()

        if not report:
            raise ValueError("No report generated by the LangGraph agents.")

        # Pass the router's task_id to MongoDB so records match the frontend
        saved_id = save_research_run(
            user_request=current_state.get("user_request", ""),
            sub_topics=current_state.get("research_plan", []),
            final_report=report,
            task_id=current_task_id, 
            latency_seconds=elapsed_latency
        )

        return {
            "status": "SUCCESS", 
            "report": report,
            "latency": elapsed_latency,
            "saved_id": saved_id,
            "task_id": current_task_id
        }

    except Exception as e:
        # Throw the exception up so routes.py can catch it and mark the task as FAILURE
        raise e