from typing import TypedDict, List, Annotated
import operator

class AgentState(TypedDict):
    # The original user prompt
    user_request: str 
    
    # The list of sub-topics generated by the Orchestrator
    research_plan: List[str]
    
    # The specific topic the Researcher is currently looking at
    current_topic: str
    
    # We use Annotated + operator.add to append new research to the list, 
    # rather than overwriting it every time the agent loops.
    collected_research: Annotated[List[str], operator.add]
    
    # The polished output from the Groq Synthesizer
    final_report: str
    
    # Safety mechanism to prevent infinite loops (costs money)
    loop_count: int